export default {
  "Change password": "Modifier mot de passe",
  "Confirm password": "Confirmer mot de passe",
  "Current password": "Mot de passe actuel",
  "Delete file": "Supprimer le fichier",
  Email: "Email",
  "Forgot password": "Mot de passe oublié",
  "Home page": "Page d'accueil",
  "Make it private": "Rendre privé",
  "Make it public": "Rendre public",
  "New password": "Nouveau mot de passe",
  Password: "Mot de passe",
  "Reset password": "Réinitialiser mot de passe",
  "Sign in": "Se connecter",
  "Sign out": "Se déconnecter",
  "My files": "Mes fichiers",
  "Upload file": "Importer un fichier",
  "Sign up": "S'inscrire",
};
