export default {
  "Change password": "Alterar palavra-passe",
  "Confirm password": "Confirmar palavra-passe",
  "Current password": "Palavra-passe atual",
  "Delete file": "Eliminar ficheiro",
  Email: "E-mail",
  "Forgot password": "Esqueceu-se da palavra-passe",
  "Home page": "Página inicial",
  "Make it private": "Tornar privado",
  "Make it public": "Tornar público",
  "New password": "Nova palavra-passe",
  Password: "Palavra-passe",
  "Reset password": "Repor palavra-passe",
  "Sign in": "Iniciar sessão",
  "Sign out": "Terminar sessão",
  "My files": "Os meus ficheiros",
  "Upload file": "Importar ficheiro",
  "Sign up": "Criar conta",
};
